doctrine_migrations:
  dir_name: "%kernel.project_dir%/src/Migrations"
  namespace: Application\Migrations
  table_name: migration_versions
  name: Application Migrations
  organize_migrations: false
  custom_template: "%kernel.project_dir%/src/AppBundle/Resources/Migrations/custom_migration.tpl"