monolog:
  channels:
    - dealerStock
    - amo
    - announcement
    - payment
    - emarsys
    - debug
    - telegramBot
    - dynamicSchedule
    - basebuy
    - leasing
    - ivideon
    - mail
    - push
    - offer
    - phone
    - slack
    - widget
    - callTouch
    - eventBus
    - notification
    - loan
    - testDrive
    - uis
    - yandex
    - carPrice
    - partnersMark
    - albato
