twig:
    default_path:         '%kernel.project_dir%/templates'
    debug:                '%kernel.debug%'
    strict_variables:     '%kernel.debug%'
    exception_controller: null
    globals:
        host:       '%host%'
        website:    '%website_domain%'
        image_base: '%image_base%'
